#!/usr/bin/env python3
"""List the names a tenant's dedicated resolver refused, and the firewall denials.

An enforced tenant cannot even resolve a name outside its policy: dnsmasq
answers it from ``local=/#/`` and logs ``config <name> is NXDOMAIN``
(``log-queries``, generated by egress_policy.py). The firewall only sees
connections to addresses, so "no denied connections" alone does not show a
missing host. Run with the tenant's DNS journal and the kernel log:

    journalctl -u mrcall-dns-<tag>.service --since '<UTC>' -o cat \\
      | python3 egress_refused.py dns
    journalctl -k --since '<UTC>' -o cat | python3 egress_refused.py deny <tag>

Prints one line per refused name (count, name) or per denied destination
(count, protocol, address, port); never resolved addresses of allowed names,
payloads or anything else from the log.
"""
from __future__ import annotations

import re
import sys
from collections import Counter

# dnsmasq: a name answered by local=/#/ ("config"), and a rebind refusal.
REFUSED = re.compile(r"\bconfig (<name unprintable>|\S+) is (?:NXDOMAIN|NODATA)")
REBIND = re.compile(r"possible DNS-rebind attack detected: (\S+)")
# netfilter log line fields, after the generated prefix.
FIELD = re.compile(r"\b(DST|PROTO|DPT)=(\S+)")
TAG = re.compile(r"[0-9a-f]{12}")


def refused_names(lines) -> Counter:
    names: Counter = Counter()
    for line in lines:
        for pattern in (REFUSED, REBIND):
            match = pattern.search(line)
            if match:
                names[match.group(1).rstrip(".").lower()] += 1
    return names


def denied(lines, tag: str) -> Counter:
    prefix = f"mc-deny-{tag} "
    seen: Counter = Counter()
    for line in lines:
        if prefix not in line:
            continue
        fields = dict(FIELD.findall(line.split(prefix, 1)[1]))
        seen[(fields.get("PROTO", "?"), fields.get("DST", "?"), fields.get("DPT", "-"))] += 1
    return seen


def main(argv: list[str]) -> int:
    if len(argv) == 2 and argv[1] == "dns":
        for name, count in sorted(refused_names(sys.stdin).items()):
            print(f"{count}\t{name}")
        return 0
    if len(argv) == 3 and argv[1] == "deny" and TAG.fullmatch(argv[2]):
        for (proto, dst, port), count in sorted(denied(sys.stdin, argv[2]).items()):
            print(f"{count}\t{proto}\t{dst}\t{port}")
        return 0
    print("usage: egress_refused.py dns | deny <12-hex tag>  (log on stdin)", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
